# Copyright 2024 The MathWorks, Inc.

version: "3.8"

services:
  network-license-manager:
    image: ghcr.io/mathworks-ref-arch/container-images/network-license-manager:latest
    # To build the image locally instead of using the hosted image,
    #  comment out the "image:" line and uncomment the "build:" line.
    # build: .
    network_mode: host
    init: true
    restart: on-failure
    volumes:
    - ./licenses:/usr/local/MATLAB/licenses/:ro
    - ./logs:/tmp/log/mathworks
